widgets: 
    -
        # Where should the widget be placed, left sidebar or right sidebar
        type: toc
        position: left
        # Whether to show the index of each heading
        index: true
        # Whether to collapse sub-headings when they are out-of-view
        collapsed: true
        # Maximum level of headings to show (1-6)
        depth: 3
    -
        type: recent_posts
        position: left
    -
        type: tags
        position: left